name: Linux C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linuxbuild:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: check g++ version
      run: g++ --version
