name: macOS C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  macosbuild:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: check g++ version
      run: g++ --version
